# =====================================================
# Head camera configuration
# =====================================================
# camera topic
head_camera:
  # if enable_zmq and enable_webrtc are both false, the camera will not start
  # Set to true to enable ZMQ publishing, false to disable
  # enable_zmq: true
  enable_zmq: false
  # Port to publish camera stream, e.g. zmq tcp://*:55555.  image_client.py should connect to the same port
  zmq_port : 55555
  # Set to true to enable WebRTC publishing, false to disable
  enable_webrtc: true
  # enable_webrtc: false
  # Port for WebRTC signaling server
  webrtc_port : 60001
  # webrtc codec preference, options: "vp8", "h264"
  webrtc_codec: h264
  type: uvc # webcam
  image_shape: [720, 1280]
  # binocular: true
  binocular: false
  # frame per second
  fps: 30

  # Camera identifiers (choose one or more):
  #   - video_id: X        → /dev/videoX  (e.g. 0 → /dev/video0)
  #   - serial_number: Y   → camera's hardware serial (e.g. 141722079879)
  #   - physical_path: Z   → sysfs physical USB path (e.g. /sys/devices/pci0000:00/.../1-11.2:1.0)
  #
  # Identifier priority:
  #   physical_path > serial_number > video_id
  #   if an identifier is not used, set it to null. The system will resolve the camera by priority.
  #
  # Notes:
  #   - type "realsense": supports serial_number only (but a RealSense can also be used as opencv/uvc if desired)
  #   - type "opencv":    supports video_id, serial_number, physical_path
  #   - type "uvc":       supports video_id, serial_number, physical_path
  # video_id: 2

  video_id: 0 
  serial_number: null
  physical_path: "/sys/devices/platform/3610000.xhci/usb1/1-2/1-2.3/1-2.3:1.0"

# =====================================================
# Left wrist camera configuration
# =====================================================
left_wrist_camera:
  enable_zmq: false
  zmq_port: 55556
  enable_webrtc: false
  webrtc_port: 60002
  webrtc_codec: h264
  type: uvc
  image_shape: [480, 640]
  binocular: false
  fps: 30
  video_id: null
  serial_number: null
  physical_path: null

# =====================================================
# Right wrist camera configuration
# =====================================================
right_wrist_camera:
  enable_zmq: false
  zmq_port: 55557
  enable_webrtc: false
  webrtc_port: 60003
  webrtc_codec: h264
  type: uvc
  image_shape: [480, 640]
  binocular: false
  fps: 30
  video_id: null
  serial_number: null
  physical_path: null
